/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests.check" instead.
 */

#include <check.h>

#include "../s21_string_files/s21_string.h"

START_TEST(s21_strcpy_test)
{
char test_1[] = "123456";
char test_2[] = "      ";
char test_3[] = "123\056";
char test_4[] = "copy\0 don't copy";
char test_5[] = "";
char test_6[] = "School 21 it's a best school of programming";
char test_7[] = "123\156";
char test_8[] = "1234567";

ck_assert_str_eq(strcpy(test_1,test_2), s21_strcpy(test_1,test_2));
ck_assert_str_eq(strcpy(test_2,test_3), s21_strcpy(test_2,test_3));
ck_assert_str_eq(strcpy(test_4,test_5), s21_strcpy(test_4,test_5));
ck_assert_str_eq(strcpy(test_5,test_4), s21_strcpy(test_5,test_4));
ck_assert_str_eq(strcpy(test_6,test_5), s21_strcpy(test_6,test_5));
ck_assert_str_eq(strcpy(test_8,test_7), s21_strcpy(test_8,test_7));

}
END_TEST

START_TEST(s21_strncpy_test)
{
char test_1[] = "123456";
char test_2[7] = "";
char test_3[] = "123\056";
char test_4[] = "copy\0 don't copy";
char test_5[17] = "";
char test_7[] = "123\156";
char test_8[] = "1234567";
char src1[] = "test test";
char dest1[] = "test_1";

ck_assert_str_eq(strncpy(test_2,test_1,3), s21_strncpy(test_2,test_1,3));
ck_assert_str_eq(strncpy(test_2,test_3,5), s21_strncpy(test_1,test_2,5));
ck_assert_str_eq(strncpy(test_5,test_4,4), s21_strncpy(test_5,test_4,4));
ck_assert_str_eq(strncpy(test_8,test_7,7), s21_strncpy(test_8,test_7,7));
ck_assert_str_eq(strncpy(test_8,test_7,4), s21_strncpy(test_8,test_7,4));
ck_assert_str_eq(strncpy(test_7,test_8,5), s21_strncpy(test_7,test_8,5));
ck_assert_str_eq(strncpy(src1,dest1,7), s21_strncpy(src1,dest1,7));
ck_assert_str_eq(strncpy(src1,dest1,6), s21_strncpy(src1,dest1,6));
ck_assert_str_eq(strncpy(src1,dest1,8), s21_strncpy(src1,dest1,8));

}
END_TEST

START_TEST(s21_strcmp_test)
{
char test_1[] = "123456";
char test_2[] = "123456";
char test_3[] = "223456";
char test_4[] = "223456_";
char test_5[] = "223456";
char test_6[] = "223656";
char test_7[] = "   ";
char test_8[] = "\\\\HH";

ck_assert_uint_eq(strcmp(test_1,test_2) == 0, s21_strcmp(test_1,test_2) == 0);
ck_assert_uint_eq(strcmp(test_2,test_3) < 0, s21_strcmp(test_2,test_3) < 0);
ck_assert_uint_eq(strcmp(test_3,test_2) > 0, s21_strcmp(test_3,test_2) > 0);
ck_assert_uint_eq(strcmp(test_3,test_4) < 0, s21_strcmp(test_3,test_4) < 0);
ck_assert_uint_eq(strcmp(test_4,test_3) > 0, s21_strcmp(test_4,test_3) > 0);
ck_assert_uint_eq(strcmp(test_6,test_5) > 0, s21_strcmp(test_6,test_5) > 0);
ck_assert_uint_eq(strcmp(test_5,test_6) < 0, s21_strcmp(test_5,test_6) < 0);
ck_assert_uint_eq(strcmp(test_7,test_8) < 0, s21_strcmp(test_7,test_8) < 0);

}
END_TEST

START_TEST(s21_strncmp_test)
{

char test_1[] = "123456";
char test_2[] = "123456";
char test_7[] = "   ";
char test_8[] = "\\\\HH";

ck_assert_uint_eq(strncmp(test_1,test_2,3), s21_strncmp(test_1,test_2,3));
ck_assert_uint_eq(strncmp(test_7,test_8,2) > 0, s21_strncmp(test_7,test_8,2) > 0);
ck_assert_uint_eq(strncmp(test_8,test_7,2) < 0, s21_strncmp(test_8,test_7,2) < 0);

}
END_TEST

START_TEST(s21_strerror_test)
{

ck_assert_str_eq(strerror(-30),s21_strerror(-30));
ck_assert_str_eq(strerror(0),s21_strerror(0));
ck_assert_str_eq(strerror(1),s21_strerror(1));
// For Mac OS
ck_assert_str_eq(strerror(107),s21_strerror(107));
ck_assert_str_eq(strerror(108),s21_strerror(108));
// For Linux
ck_assert_str_eq(strerror(130),s21_strerror(130));
ck_assert_str_eq(strerror(131),s21_strerror(131));
ck_assert_str_eq(strerror(132),s21_strerror(132));
ck_assert_str_eq(strerror(133),s21_strerror(133));

}
END_TEST

Suite *arn_test(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    // Добавление теста в группу тестов.
    
    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, s21_strcpy_test);
    tcase_add_test(tc1_1, s21_strncpy_test);
    tcase_add_test(tc1_1, s21_strcmp_test);
    tcase_add_test(tc1_1, s21_strncmp_test);
    tcase_add_test(tc1_1, s21_strerror_test);
    
    return s1;
}